- name: Login to ECR
  run: |
    echo ${{ secrets.AWS_ACCESS_KEY_ID }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
    docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/test:latest

- name: Get Latest ECR Image URI
  id: ecr
  run: |
    REPOSITORY_NAME="test"
    IMAGE_URI=$(aws ecr describe-images --repository-name $REPOSITORY_NAME --query 'images[0].imageUri' --output text)
    echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

- name: Update Task Definition
  run: |
    sed -i "s|REPLACE_WITH_IMAGE_URI|${{ env.IMAGE_URI }}|" service
    aws ecs update-service --cluster maria-dev-cluster --service maria-dev-service --task-definition service

- name: Wait for Deployment to Stabilize
  run: aws ecs wait services-stable --cluster maria-dev-cluster --services maria-dev-service
