name: 'ECR Login and Push'
description: 'Login to Amazon ECR and push Docker image'

inputs:
  registry:  
    description: 'ECR Registry URI'
    required: true
  image-name:
    description: 'Docker image name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 991108593442.dkr.ecr.$AWS_REGION.amazonaws.com/test/ec2-app /usr/bin/docker
      shell: bash
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ inputs.registry }}/${{ inputs.image-name }} .
        docker push ${{ inputs.registry }}/${{ inputs.image-name }}
      shell: bash