name: ECR Image Pull and Task Definition Update

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  update-task-definition:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY_URL }}

    - name: Pull image from ECR
      run: docker pull ${{ secrets.ECR_REGISTRY_URL }}:${{ github.sha }}

    - name: Extract ECR Image URI
      id: ecr
      run: |
        IMAGE_URI=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.ECR_REGISTRY_URL }}:${{ github.sha }})
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

    - name: Update ECS Task Definition
      run: |
        sed -i "s|REPLACE_WITH_IMAGE_URI|${{ needs.ecr.outputs.IMAGE_URI }}|" path/to/task-definition.json
        # Additional steps to update ECS task definition with the new image URI

    - name: Debug IMAGE_URI
      run: echo "IMAGE_URI: ${{ needs.ecr.outputs.IMAGE_URI }}"
