name: 'ECR Login and Push'
description: 'Login to Amazon ECR and push image'
inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true
  ecr-repository:
    description: 'ECR Repository URI'
    required: true
  registry-type:
    description: 'ECR Registry Type'
    required: false
    default: private
  image-name:
    description: 'Name of the image'
    required: true
  image-tag:
    description: 'Tag of the image'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile' 
  args:
    - ${{ inputs.aws-access-key-id }}
    - ${{ inputs.aws-secret-access-key }}
    - ${{ inputs.aws-region }}
    - ${{ inputs.ecr-repository }}
    - ${{ inputs.registry-type }}
    - ${{ inputs.image-name }}
    - ${{ inputs.image-tag }}
