name: 'ECR Login and Push'
description: 'Login to Amazon ECR and push Docker image'

inputs:
  aws-region:  
    description: 'AWS region'
    required: true
  repository:  
    description: 'ECR repository URI'
    required: true
  registry:  
    description: 'ECR Registry (public/private)'
    required: true
  image-name:
    description: 'Docker image name'
    required: true
  image-tag:
    description: 'docker image tag'
    required: true
  dockerfile:
    description: 'Dockerfile'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Script
      run: |
         chmod +x ./bash.sh
         ./bash.sh "${{ inputs.aws-region }}" "${{ inputs.repository }}" "${{ inputs.image-name }}" "${{ inputs.dockerfile }}" "${{ inputs.image-tag }}"
      shell: bash
    # - name: Login to Amazon ECR
    #   run: |
    #       aws ecr get-login-password --region ${{ inputs.aws-region }} | docker login --username AWS --password-stdin ${{ inputs.repository }}/${{ inputs.image-name }}
    #   shell: bash
    # - name: Build and Push Docker Image
    #   run: |
    #     docker build -f ${{ inputs.dockerfile }} -t ${{ inputs.image-name }}:${{ inputs.image-tag }} .
    #     docker tag ${{ inputs.image-name }}:${{ inputs.image-tag }} ${{ inputs.repository }}:${{ inputs.image-tag }}
    #     docker push ${{ inputs.repository }}:${{ inputs.image-tag }}
    #   shell: bash