name: 'ECR Login and Push'
description: 'Login to Amazon ECR and push Docker image'

inputs:
  repository:  
    description: 'ECR repository URI'
    required: true
  registry:  
    description: 'ECR Registry (public/private)'
    required: true
  image-name:
    description: 'Docker image name'
    required: true
  image-tag:
    description: 'docker image tag'
    required: true
  dockerfile-path:
    description: 'Path to the Dockerfile'
    default: "ecr-login-push/Dockerfile"
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 991108593442.dkr.ecr.$AWS_REGION.amazonaws.com/test/ec2-app 
      shell: bash
    - name: Build and Push Docker Image
      run: |
        echo "Dockerfile Path: ${{ inputs.dockerfile-path }}"
        docker build -f ${{ inputs.dockerfile-path }} -t ${{ inputs.image-name }}:${{ inputs.image-tag }} .
        docker push ${{ inputs.repository }}/${{ inputs.image-name }}:${{ inputs.image-tag }}

      shell: bash