name: 'ECR Login and Push'
description: 'Login to Amazon ECR and push Docker image'

inputs:
  repository:  
    description: 'ECR repository URI'
    required: true
  registry:  
    description: 'ECR Registry (public/private)'
    required: true
  image-name:
    description: 'Docker image name'
    required: true
  image-tag:
    description: 'docker image tag'
    required: true
  dockerfile-path:
    description: 'Path to the Dockerfile'
    default: '.'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      run: |
          export AWS_PROFILE=default
          aws ecr get-login-password --region us-east-1 --profile default | docker login --username AWS --password-stdin ${{ inputs.repository }}/${{ inputs.image-name }}
      shell: bash
    - name: Build and Push Docker Image
      run: |
        docker build -f Dockerfile -t ${{ inputs.image-name }}:${{ inputs.image-tag }} .
        docker tag ${{ inputs.image-name }}:${{ inputs.image-tag }} ${{ inputs.repository }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
        docker push ${{ inputs.repository }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
      shell: bash